// js/inventory.js - enhanced for export/import validation and preserve IDs on import
import * as Storage from './storage.js';
function uuidv4(){ if(window.crypto && crypto.randomUUID) return crypto.randomUUID(); return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){const r=Math.random()*16|0,v=c==='x'?r:(r&0x3|0x8);return v.toString(16);}); }
let state=null, subs=new Set();
function defaultState(){ return {version:1,categories:[{id:'default',name:'Default',color:'#888888'}],backpacks:{}} }
export async function init(){ const s = await Storage.loadState(); state = s? {...defaultState(), ...s} : defaultState(); notify(); return state; }
function notify(){ for(const s of subs) try{s(state);}catch(e){} }
export function subscribe(fn){ subs.add(fn); fn(state); }
export function getAllBags(){ return Object.values(state.backpacks); }
export function getBag(bid){ return state.backpacks[bid]||null; }
export function createBag({id=null,name='Mochila',owner=null,tokenId=null}={}){ const nid = id || uuidv4(); state.backpacks[nid]={id:nid,name,owner,tokenId,createdAt:Date.now(),items:[]}; Storage.saveState(null,state); notify(); return state.backpacks[nid]; }
export function addItemToBag(bagId,item,opts={}){ const bag=getBag(bagId); if(!bag) throw new Error('Bag not found'); const norm={name:String(item.name||'Unnamed'),description:String(item.description||''),category:item.category||'default',image:item.image||null,meta:item.meta||{},qty:Number(item.qty||1)}; if(!opts.forceNoStack){ for(const inst of bag.items){ if(inst.name===norm.name && (inst.image||'')===(norm.image||'') && JSON.stringify(inst.meta||{})===JSON.stringify(norm.meta||{})){ inst.qty=(inst.qty||1)+norm.qty; Storage.saveState(null,state); notify(); return inst; } } } const iid=uuidv4(); const inst={iid,...norm,createdAt:Date.now(),updatedAt:Date.now()}; bag.items.push(inst); Storage.saveState(null,state); notify(); return inst; }
export function updateItemInstance(bagId,iid,patch){ const bag=getBag(bagId); if(!bag) throw new Error('Bag not found'); const inst=bag.items.find(i=>i.iid===iid); if(!inst) throw new Error('item not found'); Object.assign(inst,patch); inst.updatedAt=Date.now(); Storage.saveState(null,state); notify(); return inst; }
export function exportData(){ return JSON.stringify(state,null,2); }
export function importData(json, {merge=false}={}){ const parsed = typeof json==='string'?JSON.parse(json):json; if(!parsed) throw new Error('Invalid JSON'); if(!merge){ state = parsed; Storage.saveState(null,state); notify(); return state; } else { state.backpacks = state.backpacks || {}; const incoming = parsed.backpacks || parsed; for(const bid of Object.keys(incoming)){ const b = incoming[bid]; let newId = b.id || bid; if(state.backpacks[newId]) newId = uuidv4(); state.backpacks[newId] = {...b, id:newId, items: b.items ? b.items.map(it => ({...it, iid: it.iid || uuidv4()})) : []}; } Storage.saveState(null,state); notify(); return state; } }
export function validateImportStructure(parsed){ if(!parsed) return {ok:false, message:'JSON vazio'}; if(parsed.type==='single-bag'){ if(!parsed.bag) return {ok:false, message:'Formato single-bag inválido: falta campo bag'}; if(!Array.isArray(parsed.bag.items)) return {ok:false, message:'Formato bag inválido: items ausente'}; return {ok:true, message:'OK'}; } if(parsed.type==='all-bags'){ if(!parsed.backpacks) return {ok:false, message:'Formato all-bags inválido: falta backpacks'}; return {ok:true, message:'OK'}; } if(parsed.backpacks && typeof parsed.backpacks==='object') return {ok:true, message:'OK'}; if(parsed.items && Array.isArray(parsed.items)) return {ok:true, message:'OK'}; return {ok:false, message:'Formato desconhecido'}; } export default { init, subscribe, getAllBags, getBag, createBag, addItemToBag, updateItemInstance, exportData, importData, validateImportStructure };